# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from proto import chat_controll_pb2 as proto_dot_chat__controll__pb2


class ChatControllStub(object):
    """ChatControll chat中控服务
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Chat = channel.unary_stream(
                '/chat_controller.ChatControll/Chat',
                request_serializer=proto_dot_chat__controll__pb2.ChatRequest.SerializeToString,
                response_deserializer=proto_dot_chat__controll__pb2.ChatReply.FromString,
                )


class ChatControllServicer(object):
    """ChatControll chat中控服务
    """

    def Chat(self, request, context):
        """Chat
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ChatControllServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Chat': grpc.unary_stream_rpc_method_handler(
                    servicer.Chat,
                    request_deserializer=proto_dot_chat__controll__pb2.ChatRequest.FromString,
                    response_serializer=proto_dot_chat__controll__pb2.ChatReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'chat_controller.ChatControll', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class ChatControll(object):
    """ChatControll chat中控服务
    """

    @staticmethod
    def Chat(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_stream(request, target, '/chat_controller.ChatControll/Chat',
            proto_dot_chat__controll__pb2.ChatRequest.SerializeToString,
            proto_dot_chat__controll__pb2.ChatReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
